    - name: Check if Docker is running
      systemd:
        name: docker
        state: started
      register: docker_status
      changed_when: false
      ignore_errors: true

    - name: Install Docker if not running
      apt:
        name: docker.io
        state: present
      when: docker_status is failed

    - name: Start Docker
      systemd:
        name: docker
        state: started
      when: docker_status is failed
      
    - name: Add user to docker group
      user:
        name: "{{ minikube-user }}"
        groups: docker
        append: true
        
    - name: Install kubectl
      shell: |
        sudo apt-get install -y ca-certificates curl
        curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update
        sudo apt-get install -y kubectl
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        "{{ dependencies }}"

    - name: Download and install Minikube
      shell: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        rm minikube-linux-amd64

    - name: Start Minikube
      shell: minikube start --driver=docker --cpus 8 --memory 10g --disk-size 20g
      become: true
      become_user: "{{ minikube_user }}"

    - name: Start Minikube addons
      shell: minikube addons enable ingress
      become: true
      become_user: "{{ minikube_user }}"
