   - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        "{{ dependencies }}"

    - name: Download and install Minikube
      shell: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        rm minikube-linux-amd64

    - name: Add user to docker group
      user:
        name: "{{ minikube_user }}"
        groups: docker
        append: true

    - name: Reset ssh connection to allow user changes to affect ansible user
      meta:
        reset_connection

    - name: Start Minikube with Docker driver
      shell: minikube start --driver=docker --cpus 8 --memory 10g --disk-size 20g
      become: true
      become_user: "{{ minikube_user }}"

    - name: Start Minikube addons
      shell: minikube addons enable ingress
      become: true
      become_user: "{{ minikube_user }}"
